package com.smartinvoice.report;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.smartinvoice.model.Invoice;
import com.smartinvoice.service.DashboardService;
import com.smartinvoice.service.InvoiceService;

import javax.swing.*;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class PdfReportGenerator {

    public static void generate() {

        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new java.io.File("SmartLedger_Report.pdf"));

        int option = chooser.showSaveDialog(null);

        if (option != JFileChooser.APPROVE_OPTION) {
            return;
        }

        try {

            Document document = new Document(PageSize.A4.rotate());

            PdfWriter.getInstance(document,
                    new FileOutputStream(chooser.getSelectedFile()));

            document.open();

            Font titleFont = new Font(Font.HELVETICA, 24, Font.BOLD);
            Font headingFont = new Font(Font.HELVETICA, 14, Font.BOLD);
            Font normalFont = new Font(Font.HELVETICA, 12);

            Paragraph title = new Paragraph(
                    "SMARTLEDGER AI\nInvoice Verification Report",
                    titleFont);

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(new Paragraph(" "));

            String date = LocalDateTime.now()
                    .format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));

            document.add(new Paragraph("Generated : " + date, normalFont));

            document.add(new Paragraph(" "));
            DashboardService dashboard = new DashboardService();

            document.add(new Paragraph(
                    "Total Invoices : "
                            + dashboard.getTotalInvoices(),
                    headingFont));

            document.add(new Paragraph(
                    "Verified Invoices : "
                            + dashboard.getVerifiedInvoices(),
                    headingFont));

            document.add(new Paragraph(
                    "Fraud Invoices : "
                            + dashboard.getFraudInvoices(),
                    headingFont));

            document.add(new Paragraph(
                    "Blockchain Blocks : "
                            + dashboard.getBlockchainBlocks(),
                    headingFont));

            document.add(new Paragraph(" "));
            PdfPTable table = new PdfPTable(5);

            table.setWidthPercentage(100);

            table.setWidths(new float[]{
                    3,4,2,2,3
            });

            addHeader(table,"Invoice No");
            addHeader(table,"Vendor");
            addHeader(table,"Amount");
            addHeader(table,"Status");
            addHeader(table,"Date");

            InvoiceService service = new InvoiceService();

            List<Invoice> invoices = service.getAllInvoices();

            for(Invoice invoice : invoices){

                table.addCell(invoice.getInvoiceNumber());
                table.addCell(invoice.getVendorName());
                table.addCell(String.valueOf(invoice.getAmount()));
                table.addCell(invoice.getStatus());
                table.addCell(invoice.getInvoiceDate());

            }

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer = new Paragraph(
                    "Generated by SmartLedger AI",
                    headingFont);

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

            JOptionPane.showMessageDialog(
                    null,
                    "PDF Report Generated Successfully!");

        }

        catch (Exception ex){

            ex.printStackTrace();

            JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage());

        }

    }

    private static void addHeader(
            PdfPTable table,
            String text){

        PdfPCell cell = new PdfPCell(
                new Phrase(text));

        cell.setHorizontalAlignment(
                Element.ALIGN_CENTER);

        table.addCell(cell);

    }

}